apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  type: LoadBalancer
  selector:
    app: grafanapod
  ports:
      - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafanapod
        type: grafanatype
    spec:
      containers: 
        - name: grafanacontainer
          image: grafana_image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - /check.sh
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: grafanapod
      type: grafanatype
