# apiVersion: v1
# kind: Service
# metadata:
#   name: influxdb-svc
# spec:
#   type: ClusterIP
#   #clusterIP: 10.99.11.11
#   selector:
#     app: influxdbPod
#   ports:
#       - port: 8086
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: influxdb
# spec:
#   template:
#     metadata:
#       name: influxdb-pod
#       labels:
#         app: influxdbPod
#         type: influxdbtype
#     spec:
#       containers: 
#         - name: influxdbcontainer
#           image: influxdb_image
#           imagePullPolicy: Never
#           ports:
#             - containerPort: 8086
#           volumeMounts:
#             - name: dockersock
#               mountPath: /var/run/docker.sock
#           livenessProbe:
#             exec:
#               command:
#                 - sh
#                 - /check.sh
#             initialDelaySeconds: 30
#             periodSeconds: 10
#       volumes:
#           - name: dockersock
#             hostPath:
#             path: /var/run/docker.sock  
#   replicas: 1
#   selector:
#     matchLabels:
#       app: influxdbPod
#       type: influxdbtype
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  type: ClusterIP
  clusterIP: 10.99.11.11
  selector:
    app: influxdbPod
  ports:
      - port: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdbPod
        type: influxdbtype
    spec:
      containers: 
        - name: influxdbcontainer
          image: influxdb_image
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: "/var/run/docker.sock"
              name: dockersock
          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - /check.sh
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock  
  replicas: 1
  selector:
    matchLabels:
      app: influxdbPod
      type: influxdbtype
