apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: twenty-one
      port: 21
      targetPort: 21
    - protocol: TCP
      name: passive
      port: 21048
      targetPort: 21048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps_image
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 21048
# apiVersion: v1
# kind: Service
# metadata:
#   name: ftps
#   annotations:
#     metallb.universe.tf/allow-shared-ip: shared
# spec:
#   type: LoadBalancer
#   ports:
#   - name: port21
#     port: 21
#     targetPort: 21
#   - name: port21000
#     port: 21048
#     targetPort: 21048
#   selector:
#     app: ftpsPod
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ftpsdeploy
# spec:
#   template:
#     metadata:
#       name: ftps-pod
#       labels:
#         app: ftpsPod
#         type: ftps
#     spec:
#       containers: 
#         - name: ftpscontainer
#           image: ftps_image
#           imagePullPolicy: Never
#           ports:
#             - name: port21
#               containerPort: 21
#             - name: port21000
#               containerPort: 21048
#           # livenessProbe:
#           #   exec:
#           #     command:
#           #       - sh
#           #       - /probe.sh
#           #   initialDelaySeconds: 30
#           #   periodSeconds: 10
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ftpsPod
#       type: ftps
