apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: twenty-one
      port: 21
      targetPort: 21
    - protocol: TCP
      name: passive
      port: 21048
      targetPort: 21048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
        type: ftpstype
    spec:
      containers: 
        - name: ftps
          image: ftps_image
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 21048
          volumeMounts:
            - mountPath: "/home/ftps"
              name: ftps
          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - /check.sh
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
      volumes:
        - name: ftps
          hostPath:
            path: /mnt/ftps
            type: Directory
  replicas: 1
  selector:
    matchLabels:
      app: ftps
      type: ftpstype

