FROM alpine:3.12
EXPOSE 5000

# add for telegraf
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories


RUN apk update
RUN apk add nginx openssl openrc telegraf && mkdir /run/nginx;
RUN apk add wget php7-common php7-iconv php7-json php7-gd php7-curl \
php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql \
php7-ctype php7-dom php php-fpm php-session php-mbstring php-gettext \
php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap


#ssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -addext "subjectAltName=DNS:localhost" \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=RU/ST=Tatarstan/L=Kazan/O=21/OU=School/CN=localhost"

# copy congig nginx
COPY ./srcs/default.conf /etc/nginx/conf.d

#copy php conf
COPY ./srcs/config.inc.php .

# copy check (for reastaart)
COPY ./srcs/check.sh .

#cope start.sh
COPY ./srcs/start.sh .

#root nginx
RUN mkdir -p /usr/share/webapps/

RUN set -x ; addgroup -g 82 -S www-data ; adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1

WORKDIR /usr/share/webapps

#donwload phpmyadmin
RUN wget http://files.directadmin.com/services/all/phpMyAdmin/phpMyAdmin-5.0.2-all-languages.tar.gz && \
tar zxvf phpMyAdmin-5.0.2-all-languages.tar.gz

RUN mv phpMyAdmin-5.0.2-all-languages phpmyadmin
RUN mv /config.inc.php /usr/share/webapps/phpmyadmin

RUN chmod -R 777 /usr/share/webapps/
RUN ln -s /usr/share/webapps/phpmyadmin/ /var/www/localhost/htdocs/phpmyadmin
#RUN ln -s /usr/share/webapps/phpmyadmin/ /var/www/html/


# rc
RUN mkdir -p /run/openrc
RUN touch /run/openrc/softlevel
#rc-service rsyslog start
#RUN openrc


WORKDIR /
ENTRYPOINT sh start.sh
